"""Split Items into FarmerBillItem and DealerBillItem

Revision ID: 1633a4a0243b
Revises: d6488ccb7923
Create Date: 2025-12-09 22:37:44.087972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1633a4a0243b'
down_revision = 'd6488ccb7923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_bill_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dealer_bill_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('quantity_bags', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['dealer_bill_id'], ['dealer_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer_bill_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_bill_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('quantity_bags', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['farmer_bill_id'], ['farmer_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('farmer_bill_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dealer_bill_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('item_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('hsn_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity_bags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dealer_bill_id'], ['dealer_bills.id'], name=op.f('items_dealer_bill_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_bill_id'], ['farmer_bills.id'], name=op.f('items_farmer_bill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.drop_table('farmer_bill_items')
    op.drop_table('dealer_bill_items')
    # ### end Alembic commands ###
