"""Add invoice fields to bills and items

Revision ID: 25c28d4d77fd
Revises: 704a36dbc2d7
Create Date: 2025-12-09 12:18:28.494144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c28d4d77fd'
down_revision = '704a36dbc2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('supply_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('place_of_supply', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('receiver_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_state_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_gstin', sa.String(), nullable=True))

    with op.batch_alter_table('farmer_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('supply_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('place_of_supply', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('receiver_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_state_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_gstin', sa.String(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quantity_bags', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('quantity_bags')
        batch_op.drop_column('hsn_code')

    with op.batch_alter_table('farmer_bills', schema=None) as batch_op:
        batch_op.drop_column('receiver_gstin')
        batch_op.drop_column('receiver_state_code')
        batch_op.drop_column('receiver_state')
        batch_op.drop_column('receiver_address')
        batch_op.drop_column('place_of_supply')
        batch_op.drop_column('supply_date')
        batch_op.drop_column('vehicle_number')
        batch_op.drop_column('transport_mode')

    with op.batch_alter_table('dealer_bills', schema=None) as batch_op:
        batch_op.drop_column('receiver_gstin')
        batch_op.drop_column('receiver_state_code')
        batch_op.drop_column('receiver_state')
        batch_op.drop_column('receiver_address')
        batch_op.drop_column('place_of_supply')
        batch_op.drop_column('supply_date')
        batch_op.drop_column('vehicle_number')
        batch_op.drop_column('transport_mode')

    # ### end Alembic commands ###
