"""Consolidate bill items into single table

Revision ID: 704a36dbc2d7
Revises: e0e70ee548c3
Create Date: 2025-12-09 11:23:14.030971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704a36dbc2d7'
down_revision = 'e0e70ee548c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_bill_id', sa.UUID(), nullable=True),
    sa.Column('dealer_bill_id', sa.UUID(), nullable=True),
    sa.Column('item', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['dealer_bill_id'], ['dealer_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_bill_id'], ['farmer_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dealer_bill_items')
    op.drop_table('farmer_bill_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_bill_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('farmer_bill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('item_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farmer_bill_id'], ['farmer_bills.id'], name=op.f('farmer_bill_items_farmer_bill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('farmer_bill_items_pkey'))
    )
    op.create_table('dealer_bill_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dealer_bill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('item_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dealer_bill_id'], ['dealer_bills.id'], name=op.f('dealer_bill_items_dealer_bill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dealer_bill_items_pkey'))
    )
    op.drop_table('items')
    # ### end Alembic commands ###
