"""Add dealer_id auto-increment column

Revision ID: a7e5ae319f11
Revises: 25c28d4d77fd
Create Date: 2025-12-09 15:29:12.377361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e5ae319f11'
down_revision = '25c28d4d77fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence('dealer_id_seq')))
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.Integer(), server_default=sa.text("nextval('dealer_id_seq')"), nullable=False))
        batch_op.create_unique_constraint(None, ['dealer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dealer_id')
    op.execute(sa.schema.DropSequence(sa.Sequence('dealer_id_seq')))

    # ### end Alembic commands ###
