"""Remove khata_no from dealers

Revision ID: e0e70ee548c3
Revises: b8209572c613
Create Date: 2025-12-09 11:02:18.673291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e70ee548c3'
down_revision = 'b8209572c613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.drop_column('khata_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('khata_no', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
