"""database schema updates

Revision ID: f5d9aa6e9ac8
Revises: change_deal_id_auto_increment
Create Date: 2025-12-11 13:06:10.397288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d9aa6e9ac8'
down_revision = 'change_deal_id_auto_increment'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'dealers', ['dealer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dealer_id')

    # ### end Alembic commands ###
